#!/usr/bin/env bash

set -eu

QIIME_CONFIG_FP="$(readlink -f data/qiime_config)"
rm ~/.qiime_config
cp "${QIIME_CONFIG_FP}" ~/.qiime_config

# manually mung old file NZGL output with python
src/py/rename_demuxed_reads.py

# check the resulting mapping file
validate_mapping_file.py \
    -m output/qiime/split_libraries/mapping.txt \
    -o output/qiime/validate_mapping \
    --disable_primer_check

# run qiime
pick_open_reference_otus.py \
    --parallel \
    --jobs_to_start 20 \
    -i output/qiime/split_libraries/seqs.fna \
    -r output/fa/rbcl_58024.fa \
    -o output/qiime/open_references

# convert biom table for R
biom convert \
    -i output/qiime/open_references/otu_table_mc2_w_tax.biom \
    -o output/qiime/open_references/otu_table_mc2_w_tax.txt \
    --to-tsv --header-key taxonomy

# if necessary, add taxonomy
parallel_assign_taxonomy_uclust.py \
    -i output/qiime/open_references/rep_set.fna \
    -o output/qiime/open_references/uclust_assigned_taxonomy -T --jobs_to_start 20
biom add-metadata \
    -i output/qiime/open_references/otu_table_mc2.biom \
    --observation-metadata-fp \
    output/qiime/open_references/uclust_assigned_taxonomy/rep_set_tax_assignments.txt \
    -o output/qiime/open_references/otu_table_mc2_w_tax.biom \
    --sc-separated taxonomy --observation-header OTUID,taxonomy
