#!/usr/bin/env bash

set -eu

QIIME_CONFIG_FP="$(readlink -f data/qiime_config)"
rm ~/.qiime_config
cp "${QIIME_CONFIG_FP}" ~/.qiime_config

validate_mapping_file.py \
    -m output/qiime/split_libraries/mapping.txt \
    -o output/qiime/validate_mapping \
    --disable_primer_check

# on original files
split_libraries.py \
    -m output/qiime/validate_mapping/test_mapping.tab_corrected.txt \
    -f previous_data/seq45R1.fasta \
    --dir_prefix output/qiime/split_libraries \
    --disable_primers \
    --min_seq_length 50

# manually mung old file
test/biopython_test_rename.py

pick_open_reference_otus.py \
    --parallel \
    --jobs_to_start 10 \
    -i output/qiime/split_libraries/seqs.fna \
    -r output/fa/rbcl_58024.fa \
    -o output/qiime/open_references

biom summarize-table \
    -i output/qiime/open_references/otu_table_mc2.biom \
    -o output/qiime/open_references/otu_table_mc2.summary.txt

summarize_taxa_through_plots.py \
    -i output/qiime/open_references/otu_table_mc2.biom \
    -m output/qiime/validate_mapping/test_mapping.tab_corrected.txt \
    -o output/qiime/summarize_taxa 

core_diversity_analyses.py \
    -i output/qiime/open_references/otu_table_mc2.biom \
    -o output/qiime/test_diversity \
    -m output/qiime/validate_mapping/test_mapping.tab_corrected.txt \
    -e 1 \
    --nonphylogenetic_diversity


